apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-gen
  template:
    metadata:
      labels:
        app: load-gen
    spec:
      containers:
      - name: load-gen
        image: docker.io/greavr/http-load-gen
        imagePullPolicy: Always
        env:
          - name: TARGET_URL
            value: "http://35.186.241.37/"
          - name: MAX_RPS
            value: "150"
          - name: DURATOIN
            value: "120"
        resources:
          limits:
            memory: 128Mi
            cpu: 500m